### ISSUE TITLE
Sort in challenge receipt page

### ISSUE THREAD

**Issue by mashannon168** [cloudspokes/direct-app#94]
In receipt page

https://www.topcoder.com/direct/contest/receipt.action?projectId=xxx

we need to list payment types in this order

winner first, then copilot, review, reliability, bugs, DR, fee, then misc (anything else).

within each type, we sort by amount in descending order.

**Comment by hohosky** [comment]
This should have been fixed in receipt page update - https://github.com/cloudspokes/direct-app/commit/dc43b8113b58a39ec3f71149ba420f94e2fa7ac0
